# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='last_name',
        ),
    ]
